# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"k\n\x05Model\x12\x1e\n\x05param\x18\x01 \x03(\x0b\x32\x0f.Model.Paramter\x1a\x42\n\x08Paramter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05n_dim\x18\x02 \x01(\x05\x12\x0b\n\x03\x64im\x18\x03 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL._serialized_start=15
  _MODEL._serialized_end=122
  _MODEL_PARAMTER._serialized_start=56
  _MODEL_PARAMTER._serialized_end=122
# @@protoc_insertion_point(module_scope)
