// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_model_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_model_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021010 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_model_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_model_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_model_2eproto;
class Model;
struct ModelDefaultTypeInternal;
extern ModelDefaultTypeInternal _Model_default_instance_;
class Model_Paramter;
struct Model_ParamterDefaultTypeInternal;
extern Model_ParamterDefaultTypeInternal _Model_Paramter_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Model* Arena::CreateMaybeMessage<::Model>(Arena*);
template<> ::Model_Paramter* Arena::CreateMaybeMessage<::Model_Paramter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Model_Paramter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Model.Paramter) */ {
 public:
  inline Model_Paramter() : Model_Paramter(nullptr) {}
  ~Model_Paramter() override;
  explicit PROTOBUF_CONSTEXPR Model_Paramter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Model_Paramter(const Model_Paramter& from);
  Model_Paramter(Model_Paramter&& from) noexcept
    : Model_Paramter() {
    *this = ::std::move(from);
  }

  inline Model_Paramter& operator=(const Model_Paramter& from) {
    CopyFrom(from);
    return *this;
  }
  inline Model_Paramter& operator=(Model_Paramter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Model_Paramter& default_instance() {
    return *internal_default_instance();
  }
  static inline const Model_Paramter* internal_default_instance() {
    return reinterpret_cast<const Model_Paramter*>(
               &_Model_Paramter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Model_Paramter& a, Model_Paramter& b) {
    a.Swap(&b);
  }
  inline void Swap(Model_Paramter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Model_Paramter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Model_Paramter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Model_Paramter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Model_Paramter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Model_Paramter& from) {
    Model_Paramter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Model_Paramter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Model.Paramter";
  }
  protected:
  explicit Model_Paramter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDimFieldNumber = 3,
    kDataFieldNumber = 4,
    kNameFieldNumber = 1,
    kNDimFieldNumber = 2,
  };
  // repeated int32 dim = 3;
  int dim_size() const;
  private:
  int _internal_dim_size() const;
  public:
  void clear_dim();
  private:
  int32_t _internal_dim(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_dim() const;
  void _internal_add_dim(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_dim();
  public:
  int32_t dim(int index) const;
  void set_dim(int index, int32_t value);
  void add_dim(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      dim() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_dim();

  // repeated float data = 4;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  float _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_data() const;
  void _internal_add_data(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_data();
  public:
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_data();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 n_dim = 2;
  void clear_n_dim();
  int32_t n_dim() const;
  void set_n_dim(int32_t value);
  private:
  int32_t _internal_n_dim() const;
  void _internal_set_n_dim(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Model.Paramter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > dim_;
    mutable std::atomic<int> _dim_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int32_t n_dim_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_2eproto;
};
// -------------------------------------------------------------------

class Model final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Model) */ {
 public:
  inline Model() : Model(nullptr) {}
  ~Model() override;
  explicit PROTOBUF_CONSTEXPR Model(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Model(const Model& from);
  Model(Model&& from) noexcept
    : Model() {
    *this = ::std::move(from);
  }

  inline Model& operator=(const Model& from) {
    CopyFrom(from);
    return *this;
  }
  inline Model& operator=(Model&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Model& default_instance() {
    return *internal_default_instance();
  }
  static inline const Model* internal_default_instance() {
    return reinterpret_cast<const Model*>(
               &_Model_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Model& a, Model& b) {
    a.Swap(&b);
  }
  inline void Swap(Model* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Model* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Model* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Model>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Model& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Model& from) {
    Model::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Model* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Model";
  }
  protected:
  explicit Model(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Model_Paramter Paramter;

  // accessors -------------------------------------------------------

  enum : int {
    kParamFieldNumber = 1,
  };
  // repeated .Model.Paramter param = 1;
  int param_size() const;
  private:
  int _internal_param_size() const;
  public:
  void clear_param();
  ::Model_Paramter* mutable_param(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Model_Paramter >*
      mutable_param();
  private:
  const ::Model_Paramter& _internal_param(int index) const;
  ::Model_Paramter* _internal_add_param();
  public:
  const ::Model_Paramter& param(int index) const;
  ::Model_Paramter* add_param();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Model_Paramter >&
      param() const;

  // @@protoc_insertion_point(class_scope:Model)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Model_Paramter > param_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Model_Paramter

// string name = 1;
inline void Model_Paramter::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Model_Paramter::name() const {
  // @@protoc_insertion_point(field_get:Model.Paramter.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Model_Paramter::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Model.Paramter.name)
}
inline std::string* Model_Paramter::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Model.Paramter.name)
  return _s;
}
inline const std::string& Model_Paramter::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Model_Paramter::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Model_Paramter::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Model_Paramter::release_name() {
  // @@protoc_insertion_point(field_release:Model.Paramter.name)
  return _impl_.name_.Release();
}
inline void Model_Paramter::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Model.Paramter.name)
}

// int32 n_dim = 2;
inline void Model_Paramter::clear_n_dim() {
  _impl_.n_dim_ = 0;
}
inline int32_t Model_Paramter::_internal_n_dim() const {
  return _impl_.n_dim_;
}
inline int32_t Model_Paramter::n_dim() const {
  // @@protoc_insertion_point(field_get:Model.Paramter.n_dim)
  return _internal_n_dim();
}
inline void Model_Paramter::_internal_set_n_dim(int32_t value) {
  
  _impl_.n_dim_ = value;
}
inline void Model_Paramter::set_n_dim(int32_t value) {
  _internal_set_n_dim(value);
  // @@protoc_insertion_point(field_set:Model.Paramter.n_dim)
}

// repeated int32 dim = 3;
inline int Model_Paramter::_internal_dim_size() const {
  return _impl_.dim_.size();
}
inline int Model_Paramter::dim_size() const {
  return _internal_dim_size();
}
inline void Model_Paramter::clear_dim() {
  _impl_.dim_.Clear();
}
inline int32_t Model_Paramter::_internal_dim(int index) const {
  return _impl_.dim_.Get(index);
}
inline int32_t Model_Paramter::dim(int index) const {
  // @@protoc_insertion_point(field_get:Model.Paramter.dim)
  return _internal_dim(index);
}
inline void Model_Paramter::set_dim(int index, int32_t value) {
  _impl_.dim_.Set(index, value);
  // @@protoc_insertion_point(field_set:Model.Paramter.dim)
}
inline void Model_Paramter::_internal_add_dim(int32_t value) {
  _impl_.dim_.Add(value);
}
inline void Model_Paramter::add_dim(int32_t value) {
  _internal_add_dim(value);
  // @@protoc_insertion_point(field_add:Model.Paramter.dim)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Model_Paramter::_internal_dim() const {
  return _impl_.dim_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Model_Paramter::dim() const {
  // @@protoc_insertion_point(field_list:Model.Paramter.dim)
  return _internal_dim();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Model_Paramter::_internal_mutable_dim() {
  return &_impl_.dim_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Model_Paramter::mutable_dim() {
  // @@protoc_insertion_point(field_mutable_list:Model.Paramter.dim)
  return _internal_mutable_dim();
}

// repeated float data = 4;
inline int Model_Paramter::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int Model_Paramter::data_size() const {
  return _internal_data_size();
}
inline void Model_Paramter::clear_data() {
  _impl_.data_.Clear();
}
inline float Model_Paramter::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline float Model_Paramter::data(int index) const {
  // @@protoc_insertion_point(field_get:Model.Paramter.data)
  return _internal_data(index);
}
inline void Model_Paramter::set_data(int index, float value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:Model.Paramter.data)
}
inline void Model_Paramter::_internal_add_data(float value) {
  _impl_.data_.Add(value);
}
inline void Model_Paramter::add_data(float value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:Model.Paramter.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Model_Paramter::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Model_Paramter::data() const {
  // @@protoc_insertion_point(field_list:Model.Paramter.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Model_Paramter::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Model_Paramter::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Model.Paramter.data)
  return _internal_mutable_data();
}

// -------------------------------------------------------------------

// Model

// repeated .Model.Paramter param = 1;
inline int Model::_internal_param_size() const {
  return _impl_.param_.size();
}
inline int Model::param_size() const {
  return _internal_param_size();
}
inline void Model::clear_param() {
  _impl_.param_.Clear();
}
inline ::Model_Paramter* Model::mutable_param(int index) {
  // @@protoc_insertion_point(field_mutable:Model.param)
  return _impl_.param_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Model_Paramter >*
Model::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:Model.param)
  return &_impl_.param_;
}
inline const ::Model_Paramter& Model::_internal_param(int index) const {
  return _impl_.param_.Get(index);
}
inline const ::Model_Paramter& Model::param(int index) const {
  // @@protoc_insertion_point(field_get:Model.param)
  return _internal_param(index);
}
inline ::Model_Paramter* Model::_internal_add_param() {
  return _impl_.param_.Add();
}
inline ::Model_Paramter* Model::add_param() {
  ::Model_Paramter* _add = _internal_add_param();
  // @@protoc_insertion_point(field_add:Model.param)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Model_Paramter >&
Model::param() const {
  // @@protoc_insertion_point(field_list:Model.param)
  return _impl_.param_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_model_2eproto
